### ISSUE TITLE
[META] Document and automate release process

### ISSUE THREAD

**Issue by DanHatesNumbers** [simplybusiness/Kiln#44]
The process for releasing Kiln should be automated as part of Github Actions CI.

Manual steps
- Open a release branch from master
- Update version number in all crates Cargo.toml files with next semver version number based on changes
- Swap dependencies on Kiln_lib from git-master to git-tag
- Update CHANGELOG.md
- Tag commit with SemVer version number and sign using your GPG key
- Push commits and tag
- Revert kiln_lib dependencies from git-tag back to git-master
- Merge to master

CI then performs following:

- Checkout the repo to the latest release tag
- Ensure GPG installed
- Import release public keys from meta/release-keys
- Verify signature on the release tag to ensure it was created by a trusted releaser
- Archive contents of repo and upload to Github Releases, compute hash of archive and upload to Github Releases, make detached signature of hash and upload to Github Releases
- Build CLI app for Linux and MacOS, build deb and rpm packages, sync to public repo and update custom Homebrew tap
- Build all docker images with latest, datestamp and SemVer tags (including the version of tools where appropriate) and push to Docker Hub

Outstanding Tasks:
- [x] Write release documentation (#87)
- [ ] Setup releasers with GPG keys and add to repo
- [x] Change naming format of Docker image builds (#88)
- [x] Turn on building and pushing Docker images on merge to master
- [x] Create GPG signing key for automation use
- [ ] Create S3 bucket and CF distribution to host Apt and Yum repos
- [ ] Automate release process with Github Actions
- [ ] Test release process with an Alpha version
- [ ] Update release process documentation
- [ ] Add installation instructions to README.md

**Comment by DanHatesNumbers** [comment]
Alternative process:

- Open release branch
- Update crate version numbers
- Update Changelog
- Merge branch to master (triggers CI for branch to ensure everything builds)
- Tag commit and push tag
- Add CI workflow for tag push to build CLI binary and publish it to GH releases, build Docker images and push to Github Packages, tarball repo and add to GH releases

**Comment by DanHatesNumbers** [comment]
Ideally, I'd like to ensure that tags that a release will be built from are signed tags

**Comment by DanHatesNumbers** [comment]
In order to enforce tag signing, we'd need to include a copy of the public keys of trusted contributors who will be releasing Kiln, then in Github Actions, the Release workflow will need to checkout the tag that triggered the run, import the trusted keys into GPG, run git verify-tag and only then proceed with the release workflow.

**Comment by DanHatesNumbers** [comment]
Adding signed tags are a requirement for release will need some documentation on generating a GPG key, uploading it to GitHub, how to sign a tag etc. Tag signing should probably live with the release documentation, but setup should be separate,

**Comment by DanHatesNumbers** [comment]
Before we can release
* Test that CLI app builds on MacOS, Windows and Linux
* Write installation script
    * Can we script installation and PATH modification on Windows?
* Test release process with an Alpha version
* Add installation instructions to README.md
* Add documentation of how docker images are versioned and the naming format in Kiln

**Comment by DanHatesNumbers** [comment]
Creating a release an uploading artifacts: 

- https://github.com/actions/create-release
- https://www.github.com/actions/upload-release-asset

**Comment by DanHatesNumbers** [comment]
Install script thoughts:

1. Figure out how we can download binary (curl, wget, python?), if no option, abort
2. Figure out if we can do gpg signature verification on host, warn if we can't
3. Figure out what platform we're on
4. Detect if binary is already installed and if so, check current version
5. Check what latest version is on Github, if version isn't newer, abort
6. Pushd to /tmp
7. Download binary for platform using available method
8. If we can do gpg signature verification, download hashes and detached signatures
9. If we can do gpg signature verification, perform signature verification, if it fails, abort
10. Copy binary to /usr/local/bin, overwriting old version if needed

**Comment by DanHatesNumbers** [comment]
Blocked in #16

**Comment by DanHatesNumbers** [comment]
When building the Installer script, for MacOS testing, these projects will be helpful for creating a repeatable testing environment: 

https://github.com/bacongravy/macinbox
https://github.com/munki/macadmin-scripts/blob/master/installinstallmacos.py

**Comment by DanHatesNumbers** [comment]
Useful blog post on how to maintain a homebrew tap for pre-built binaries to avoid users having to compile from source:https://jonathanchang.org/blog/maintain-your-own-homebrew-repository-with-binary-bottles/

**Comment by DanHatesNumbers** [comment]
Useful blog post on getting MacOS Cross Compilation with OpenSSL working on linux: http://timryan.org/2018/07/27/cross-compiling-linux-binaries-from-macos.html

**Comment by DanHatesNumbers** [comment]
Automating this process is turning out to be more complex than originally planned. I'm going to close this issue and open a new one to cover the work to document a manual release process based on what I've learnt from attempting to automate the process.
